baseurl: ""
markdown: redcarpet

brigade:
    name: Code for Seattle
    city:   "Seattle, WA"
    meetup-link: "http://www.meetup.com/Code-for-Seattle/"
    google-group: "https://groups.google.com/forum/#!forum/codeforseattle"
    github: "https://github.com/codeforseattle"
    idea-list: "http://seattlewiki.net/Code_for_Seattle_ideas"

content:
    title: Code for Seattle
    meetup-invite: "http://www.meetup.com/Code-for-Seattle/"
    contact: "info@seattlewiki.net"
    banner: ./images/banner.jpg
    projects:
      - name: "SeattleWiki.net"
        card-img: "http://i.imgur.com/DedjCpj.png"
        link: "http://seattlewiki.net"
      - name: "nwdata.org"
        card-img: "http://imgur.com/p7l8hVM.png"
        link: "http://nwdata.org"
      - name: "Seattle Food Trucks"
        card-img: "http://i.imgur.com/hTSG6AI.png"
        link: "http://seattlefoodtrucks.herokuapp.com/"
      - name: "GeoSub"
        card-img: "http://i.imgur.com/dztXym2.png"
        link: "https://github.com/willscott/geosub"
      - name: "Seattle Blogs API"
        card-img: "http://i.imgur.com/D4DTWFw.png"
        link: "http://seattle-blogs.herokuapp.com/"
      - name: "Ruby LocalWiki client"
        card-img: "http://imgur.com/JUygPil.png"
        link: "https://github.com/codeforseattle/localwiki_client"
      - name: "Node.js LocalWiki client"
        card-img: "http://imgur.com/FTCRgDE.png"
        link: "https://github.com/codeforseattle/node-localwiki-client"
    footer: "Thanks to Virginia Beach CfA for supplying this site's template, the Noun Project and brockamer@flikr for images,</br> and Jan Jorgensen for converting the template to Jekyll." 

google-analytics:
    use: true
    code: UA-38362883-1
